[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[markup.highlight]
guessSyntax = true
noClasses = false

[params]
  clipboard = { success = "复制成功(*^▽^*)", fail = "复制失败 (ﾟ⊿ﾟ)ﾂ" }
  copyright = { enable = false, count = 50, content = "本文版权：本博客所有文章除特别声明外，均采用 BY-NC-SA 许可协议。转载请注明出处！" }

[markup.goldmark.extensions.passthrough]
  enable = true
  delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
  delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup]
  [markup.goldmark]
    unsafe = true


